name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - name: Install GPG
        run: sudo apt-get update && sudo apt-get install gnupg -y

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Import GPG private key
        run: |
          mkdir -p ~/.gnupg
          echo "${{ secrets.ENCRYPTED_PRIVATE_KEY }}" > private_key.asc
          chmod 700 ~/.gnupg
          gpg --batch --yes --import private_key.asc

      - name: Use decrypted private key
        run: gpg --import private_key.asc

      - name: Decrypt GPG-encrypted File
        run: |
          if ! gpg --decrypt --output secrets.tfvars secrets.tfvars.gpg; then
            echo "Failed to decrypt the file."
            exit 1
          fi

      - name: Set up AWS credentials
        run: |
          echo "[worth-staging-admin]" >> ~/.aws/credentials
          echo "aws_access_key_id=ASIA3ONR34RQWFVN4RHS" >> ~/.aws/credentials
          echo "aws_secret_access_key=ZhoFJHA+EseSAZ/JaNlL69FPLRMV7I9OtMyF0pBT" >> ~/.aws/credentials
          echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: |
          terraform plan -var-file="variables.tfvars" -var-file="secrets.tfvars" -auto-approve
