name: VPN and Update Kubeconfig for EKS Cluster

on:
  workflow_dispatch:

jobs:
  connect-vpn-and-update-kubeconfig:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn

      - name: Set up OpenVPN
        env:
          OVPN_CONFIG: ${{ secrets.OVPN_CONFIG }}
        run: |
          echo "$OVPN_CONFIG" > vpn.ovpn  # Write the secret to a file
          sudo openvpn --config vpn.ovpn --verb 3
          sleep 30

      - name: Check VPN Connection
        run: |
          if sudo openvpn --config vpn.ovpn --status | grep 'CONNECTED'; then
            echo "VPN is successfully connected."
          else
            echo "VPN is not connected. Please check the connection."
            exit 1
          fi

      - name: Check Connectivity to Google
        run: |
          ping -c 4 google.com || true

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[worth-prod-admin]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_ACCESS_KEY_SECRET }}" >> ~/.aws/credentials

      # - name: Install ArgoCD CLI
      #   run: |
      #     wget https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 -O /usr/local/bin/argocd
      #     chmod +x /usr/local/bin/argocd

      # - name: Verify ArgoCD CLI installation
      #   run: |
      #     argocd version

      - name: Install kubectl CLI
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      - name: Verify kubectl CLI installation
        run: |
          kubectl version --client

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region us-east-1 --name worthai-prod-ekscluster --profile worth-prod-admin

      - name: Create namespace for ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl create namespace services
