name: VPN and Update Kubeconfig for EKS Cluster

on:
  workflow_dispatch:

jobs:
  connect-vpn-and-update-kubeconfig:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn

      - name: Connect to VPN
        uses: kota65535/github-openvpn-connect-action@v2
        with:
          config_file: .github/workflows/client.ovpn

      - name: Verify VPN Connection
        run: |
          curl ifconfig.me
          cat /etc/resolv.conf
          
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install kubectl CLI
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl

      # - name: Setup ArgoCD CLI
      #   uses: imajeetyadav/argocd-cli@v1

      # - name: Check ArgoCD CLI
      #   run: argocd version

      - name: Set up AWS credentials
        run: |
          mkdir -p ~/.aws
          echo "[worth-prod-admin]" >> ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_ACCESS_KEY_SECRET }}" >> ~/.aws/credentials

      - name: Update kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --region us-east-1 --name worthai-prod-ekscluster --profile worth-prod-admin

      - name: AWS configure
        run: |
          aws configure list --region us-east-1 --profile worth-prod-admin
          
      - name: List s3 bucket
        run: |
          aws s3 ls --region us-east-1 --profile worth-prod-admin
          
      - name: Create namespace for ArgoCD
        run: |
          kubectl create namespace argocd
          kubectl create namespace services
